console.log('\nConstructor Design Pattern')
require('./constructor')
console.log('\nModule Design Pattern')
require('./module')
console.log('\nRevealing Module Design Pattern')
require('./revealing_module')
