const { title } = require('./utils')
title('1. Constructor Design Pattern'); require('./constructor')
title('2. Module Design Pattern'); require('./module')
title('3. Revealing Module Design Pattern'); require('./revealing_module')
title('4. Singleton Design Pattern'); require('./singleton')
